server:
  port: 8088
spring:
  application:
    name: orderservice
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        #cluster-name: HZ
        #namespace: ca6dac88-8a63-430d-afad-96e0ce9a61d9 #dev环境
        ephemeral: true #是否是临时实例
    sentinel:
      transport:
        dashboard: localhost:8080
      web-context-unify: false # 关闭context
      datasource:
        flow:
          nacos:
            server-addr: localhost:8848 # nacos地址
            dataId: orderservice-flow-rules
            groupId: SENTINEL_GROUP
            rule-type: flow # 还可以是：degrade、authority、param-flow
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
#eureka:
#  client:
#    service-url: # eureka地址信息
#      defaultZone: http://127.0.0.1:10086/eureka/
userservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule
ribbon:
  eager-load:
    enabled: true #饥饿加载
    clients:
      - userservice
feign:
  httpclient:
    enabled: true #支持httpclient
    max-connections: 200
    max-connections-per-route: 50
  sentinel:
    enabled: true # 开启支持