logging:
  pattern:
    dateformat: HH:mm:ss:SSS
  level:
    cn.itcast: debug
spring:
  rabbitmq:
#    host: 192.168.13.10 # rabbitMQ的ip地址
#    port: 5672 # 端口
    addresses: 192.168.13.10:8071, 192.168.13.10:8072, 192.168.13.10:8073
    username: root
    password: 1234
    virtual-host: /
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: auto
        retry:
          enabled: true
          initial-interval: 1000
          multiplier: 3
          max-attempts: 4

